{
    "alloy": {
    "title": "Alloy",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Alloy+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/alloy_armor_set_mhw_small.png",
    "resistances": "Defense 40\n Fire -10\n Water 5\n Thunder -10\n Ice -10\n Dragon 5",
    "setBonus": "None",
    "headSkills": "Windproof 1x",
    "chestSkills: Water Resistance 1x",
    "armSkills": "Defense Boost 1x",
    "waistSkills": "Poison Resistnce 1x",
    "legSkills": "Speed Sharpening"
  },
    "anja": {
    "title": "Anja",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Anja+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/anja_armor_set_mhw_small.png",
    "resistances": "Defense 100\n Fire 15\n Water -15\n Thunder -5\n Ice -5\n Dragon 0",
    "setBonus": "Anjanath Power: Temporarily reduces stamina depletion when health is at 40% or lower",
    "headSkills": "Fire Attack 1x",
    "chestSkills": "Marathon Runner 1x",
    "armSkills": "Special Ammo Boost 1x",
    "waistSkills": "Fire Resistance 1x",
    "legSkills": "Artillery 1x"
  },
    "baan": {
    "title": "Baan",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Baan+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/baan_armor_set_mhw_small.png",
    "resistances": "Defense 120\n Fire 0\n Water 10\n Thunder 0\n Ice -5\n Dragon -10",
    "setBonus": "None",
    "headSkills": "Slugger 1x",
    "chestSkills": "Sleep Resistance 1x",
    "armSkills": "Sleep Attack 1x",
    "waistSkills": "Guard 1x",
    "legSkills": "Bleeding Resistance 1x"
  },
    "barroth": {
    "title": "Barroth",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Barroth+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barroth_armor_set_mhw_small.png",
    "resistances": "Defense 70\n Fire -15\n Water -5\n Thunder 15\n Ice -5\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Guard 1x",
    "chestSkills": "Stamina Thief 1x",
    "armSkills": "Marathon Runner 1x",
    "waistSkills": "Muck Resistance 1x",
    "legSkills": "Stun Resistance"
  },
    "blossom": {
    "title": "Blossom",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Blossom+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/blossom_armor_set_mhw_small.png",
    "resistances": "Defense 90\n Fire 5\n Water 5\n Thunder 20\n Ice 5\n Dragon 5\n",
    "setBonus": "None",
    "headSkills": "Honey Hunter",
    "chestSkills": "Quick Sheath",
    "armSkills": "Paralysis Resistance",
    "waistSkills": "Scoutfly Range Up",
    "legSkills": "Recovery Speed"
  },
    "bone": {
    "title": "Bone",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Bone+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/bone_armor_set_mhw_small.png",
    "resistances": "Defense 30\n Fire 10\n Water 0\n Thunder 10\n Ice 0\n Dragon 10",
    "setBonus": "None",
    "headSkills": "Health Boost 1x",
    "chestSkills": "Attack Boost 1x",
    "armSkills": "Slugger 1x",
    "waistSkills": "Horn Maestro 1x",
    "legSkills": "Entomologist 1x"
  },
    "butterfly": {
    "title": "Butterfly",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Butterfly+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/butterfly_armor_set_mhw_small.png",
    "resistances": "Defense 110\n Fire -5\n Water -5\n Thunder 10\n Ice 0\n Dragon 10",
    "setBonus": "None",
    "headSkills": "Evade Window 1x",
    "chestSkills": "Quick Sheath 1x",
    "armSkills": "Leap of Faith 1x",
    "waistSkills": "Honey Hunter 1x",
    "legSkills": "Forager's Luck 1x"
  },
    "chainmail": {
    "title": "Chainmail",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Chainmail+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/chainmail_armor_set_mhw_small.png",
    "resistances": "Defense 10\n Fire 0\n Water 10\n Thunder 0\n Ice 0\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Master Gatherer 1x",
    "chestSkills": "None",
    "armSkills": "None",
    "waistSkills": "None",
    "legSkills": "None"
  },
    "deathstench": {
    "title": "Death Stench",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Death+Stench+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/death_stench_armor_set_mhw_small.png",
    "resistances": "Defense 160\n Fire 15\n Water 10\n Thunder -10\n Ice 15\n Dragon -20",
    "setBonus": "None",
    "headSkills": "Resuscitate 1x",
    "chestSkills": "Fortify 1x",
    "armSkills": "Focus 1x",
    "waistSkills": "Dragon Attack 1x",
    "legSkills": "Handicraft 1x"
  },
    "diablos": {
    "title": "Diablos",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Diablos+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/diablos_armor_set_mhw_small.png",
    "resistances": "Defense 160\n Fire 15\n Water -10\n Thunder 0\n Ice -15\n Dragon 10",
    "setBonus": "Raises attack as your weapon loses sharpness. Also boost ranged weapon melee attacks and odds of stunning",
    "headSkills": "Critical Draw 1x",
    "chestSkills": "Slugger 1x",
    "armSkills": "Heroics 1x",
    "waistSkills": "Marathon Runner 1x",
    "legSkills": "Tremor Resistance 1x"
  },
    "diver": {
    "title": "Diver",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Diver+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/divers_armor_set_mhw_small.png",
    "resistances": "Defense 110\n Fire 5\n Water 20\n Thunder 5\n Ice 5\n Dragon 5",
    "setBonus": "None",
    "headSkills": "Marathon Runner 1x",
    "chestSkills": "Critical Eye 1x",
    "armSkills": "Quick Sheath 1x",
    "waistSkills": "Aquatic Expert 1x",
    "legSkills": "Hunger Resistance 1x"
  },
    "galasuit": {
    "title": "Gala Suit",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Gala+Suit+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gala-armor-mhw-wiki-guide2.png",
    "resistances": "Defense 170\n Fire 5\n Water 5\n Thunder 5\n Ice 5\n Dragon 20",
    "setBonus": "Astera Blessing 5x",
    "headSkills": "Critical Boost 1x",
    "chestSkills": "Critical Draw 1x",
    "armSkills": "Maximum Might 1x",
    "waistSkills": "Slinger Capacity 1x",
    "legSkills": "Divine Blessing 1x"
  },
    "gajau": {
    "title": "Gajau",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Gajau+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gajau_alpha_armor_set_mhw_small.png",
    "resistance": "Defense 12\n Fire 0\n Water 5\n Thunder 0\n Ice 0\n Dragon 0",
    "setBonus": "None",
    "legSkills": "Aquatic Expert 1x"
  },
    "girros": {
    "title": "Girros",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Girros+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/girros_armor_set_mhw_small.png",
    "resistances": "Defense 100\n Fire 0\n Water -15\n Thunder 10\n Ice 0\n Dragon 5",
    "setBonus": "None",
    "headSkills": "Horn Maestro 1x",
    "chestSkills": "Paralysis Resistance 1x",
    "armSkills": "Palico Rally 1x",
    "waistSkills": "Effluvial Expert 1x",
    "legSkills": "Paralysis Attack 1x"
  },
    "guardian": {
    "title": "Guardian",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Guardian+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/guardian-armor_iceborne-mhw-wiki-guide.png",
    "resistances": "Defense 250\n Fire 10\n Water 0\n Thunder 0\n Ice 10/n Dragon 15",
    "setBonus": "None",
    "headSkills": "Recovery Up 2x\n Health Boost 1x",
    "chestSkills": "Marathon Runner 1x\n Recovery Up 1x",
    "armSkills": "Marathon Runner 1x\n Divine Blessing 1x",
    "waistSkills": "Health Boost 2x\n Divine Blessing 1x",
    "legSkills": "Marathon Runner 1x\n Divine Blessing 1x"
  },
    "highmetal": {
    "title": "High Metal",
    "url": "https://monsterhunterworld.wiki.fextralife.com/High+Metal+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/high_metal_armor_set_mhw_small.png",
    "resistances": "Defense 90\n Fire 0\n Water -5\n Thunder -10\n Ice -15\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Ice Resistanc 1x",
    "chestSkills": "Earplugs 1x",
    "armSkills": "Defense Boost 1x",
    "waistSkills": "Capacity Boost 1x",
    "legSkills": "Heavy Artillery 1x"
  },
    "harvest": {
    "title": "Harvest",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Harvest+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/harvest-armor-mhw-wiki-guide2.png",
    "resistances": "Defense 130\n Fire 20\n Water 5\n Thunder 5\n Ice 5\n Dragon 5",
    "setBonus": "None",
    "headSkills": "Tremor Resistance 1x",
    "chestSkills": "Focus 1x",
    "armSkills": "Resentment 1x",
    "waistSkills": "Constitution 1x",
    "legSkills": "Mushroomancer 1x"
  },
    "hornetaur": {
    "title": "Hornetaur",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Hornetaur+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/hornetaur_armor_set_mhw_small.png",
    "resistances": "Defense 90\n Fire -5\n Water -5\n Thunder 0\n Ice 0\n Dragon 10",
    "setBonus": "None",
    "headSkills": "Dungmaster 1x",
    "chestSkills": "Effluvia Expert 1x",
    "armSkills": "Free Meal 1x",
    "waistSkills": "Carving Pro 1x",
    "legSkills": "Handicraft 1x"
  },
    "hunter'sarmor": {
    "title": "Hunter's Armor",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Hunter's+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/hunters_armor_set_mhw_small.png",
    "resistances": "Defense 30\n Fire 10\n Water 10\n Thunder 0\n Ice 0\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Scoutfly Range Up 1x",
    "chestSkills": "Slinger Capacity 1x",
    "armSkills": "Stealth 1x",
    "waistSkills": "Scenthound 1x",
    "legSkills": "BBQ Master 1x"
  },
    "ingot": {
    "title": "Ingot",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Ingot+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ingot_armor_set_mhw_small.png",
    "resistances": "Defense 140\n Fire -10\n Water 0\n Thunder 15\n Ice -5\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Thunder Attack 1x",
    "chestSkills": "Thunder Resistance 1x",
    "armSkills": "Health Boost 1x",
    "waistSkills": "Windproof 1x",
    "legSkills": "Defense Boost 1x"
  },
    "jagras": {
    "title": "Jagras",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Jagras+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jagras_armor_set_mhw_small.png",
    "resistances": "Defense 40\n Fire -10 Water 10\n Thunder -5\n Ice 5\ Dragon 5",
    "setBonus": "None",
    "headSkills": "Speed Eating 1x",
    "chestSkills": "Intimidator 1x",
    "armSkills": "Palico Rally 1x",
    "waistSkills": "Fortify 1x",
    "legSkills": "Speed Crawler 1x"
  },
    "jyura": {
    "title": "Jyura",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Jyura+Armor+Set",
    "thumbnail" :"https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jyura_armor_set_mhw_small.png",
    "resistances": "Defense 70\n Fire -5\n Water 10\n Thunder -15\n Ice 0\n Dragpn 0",
    "setBonus": "None",
    "headSkills": "Aquati Expert 1x",
    "chestSkills": "Muck Resistance 1x",
    "armSkills": "Water Attack 1x",
    "waistSkills": "Ice Resistance 1x",
    "legSkills": "Focus 1x"
  },
    "kadachi": {
    "title": "Kadachi",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Kadachi+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kadachi_armor_set_mhw_small.png",
    "resistances": "Defense 81\n Fire 0\n Water -15\n Thunder 15\n Ice 0\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Constitution 1x",
    "chestSkills": "Jump Master 1x",
    "armSkills": "Evade Extender 1x",
    "waistSkills": "Thunder Attack 1x",
    "legSkills": "Thunder Resistance 1x"
  },
    "kestodon": {
    "title": "Kestodon",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Kestodon+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kestodon_armor_set_mhw_small.png",
    "resistances": "Defense 12\n Fire 4\n Water 0\n Thunder 0\n Ice 0\n Dragon 0",
    "setBonus": "None",
    "armSkills": "Affinity Sliding 1x"
  },
    "kingbeetle": {
    "title": "King Beetle",
    "url": "https://monsterhunterworld.wiki.fextralife.com/King+Beetle+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/king_beetle_armor_set_mhw_small.png",
    "resistances": "Defense 110\n Fire -5\n Water -5\n Thunder 10\n Ice 0\n Dragon 10",
    "setBonus": "None",
    "headSkills": "Evade Window 1x",
    "chestSkills": "Quick Sheath 1x",
    "armSkills": "Botanist 1x",
    "waistSkills": "Honey Hunter 1x",
    "legSkills": "Forager's Luck 1x"
  },
    "kirin": {
    "title": "Kirin",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Kirin+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kirin_armor_set_mhw_small.png",
    "resistances": "Defense 170\n Fire -15\n Water -10\n Thunder 20\n Ice -10\n Dragon 10",
    "setBonus": "High chance of increased capture rewards (no effect when joining mid-quest)",
    "headSkills": "Marathon Runner 1x",
    "chestSkills": "Divine Blessing 1x",
    "armSkills": "Blight Resistance 1x",
    "waistSkills": "Thunder Attack 1x",
    "legSkills": "Thunder Resistance 1x"
  },
    "kulu": {
    "title": "Kulu",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Kulu+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulu_armor_set_mhw_small.png",
    "resistances": "Defense 50\n Fire 0\n Water -15\n Thunder 0\n Ice 5\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Fire Resistance 1x",
    "chestSkills": "Stamina Surge 1x",
    "armSkills": "Pro Transporter 1x",
    "waistSkills": "Item Prolonger 1x",
    "legSkills": "Critical Eye 1x"
  },
    "leather": {
    "title": "Leather",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Leather+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/placeholder-armor-set-mhw-wiki.jpg",
    "resistances": "Defense 10\n Fire 10\n Water 0\n Thunder 0\n Ice 0\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Hunger Resistance 1x",
    "chestSkills": "None",
    "armSkills": "None",
    "waistSkills": "None",
    "legSkills": "None"
  },
    "legiana": {
    "title": "Legiana",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Legiana+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/legiana_armor_set_mhw_small.png",
    "resistance": "Defense 150\n Fire -5\n Water 10\n Thunder -15\n Ice 15\n Dragon 0",
    "setBonus": "Good chance of increased quest rewards (no effect when joining mid-quest)",
    "headSkills": "Divine Blessing 1x",
    "chestSkills": "Evade Window 1x",
    "armSkills": "Airborne 1x",
    "waistSkills": "Ice Resistance 1x",
    "legSkills": "Ice Attack 1x"
  },
    "lumu": {
    "title": "Lumu",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Lumu+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lumu_armor_set_mhw_small.png",
    "resistances": "Defense 100\n Fire -15\n Water 10\n Thunder 0\n Ice 5\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Stamina Surge 1x",
    "chestSkills": "Master Mounter 1x",
    "armSkills": "Artillery 1x",
    "waistSkills": 'Divine Blessing 1x",
    "legSkills": "Windproof 1x"
  },
    "odogaron": {
    "title": "Odogaron",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Odogaron+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/odogaron_armor_set_mhw_small.png",
    "resistances": "Defense 150\n Fire 10\n Water 10\n Thunder -10\n Ice -15\n Dragon 0",
    "setBonus": "Adds a stun effect to draw attacks and slightly increases attack power",
    "headSkills": "Bleeding Resistance 1x",
    "chestSkills": "Speed Sharpening 1x",
    "armSkills": "Constitution 1x",
    "waistSkills": "Critical Eye 1x",
    "legSkills": "Quick Sheath 1x"
  },
    "origin": {
    "title": "Origion",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Origin+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/origin-armor-mhw-wiki-guide2.png",
    "resistances": "Defense 31\n Fire 0\n Water 0\n Thunder 0\n Ice 0\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Forager's Luck",
    "chestSkills": "None",
    "armSkills": "None",
    "waistSkills": "None",
    "legSkills": "None"
  },
    "pukei": {
    "title": "Pukei",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Pukei+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/pukei_armor_set_mhw_small.png",
    "resistances": "Defense 60\n Fire 0\n Water 15\n Thunder -15\n Ice 0\n Dragon 5",
    "setBonus": "None",
    "headSkills": "Sporepuff Expert 1x",
    "chestSkills": "Item Proloner 1x",
    "armSkills": "Poison Resistance 1x",
    "waistSkills": "Poison Attack 1x",
    "legSkills": "Botanist 1x"
  },
    "rathalos": {
    "title": "Rathalos",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Rathalos+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathalos_armor_set_mhw_small.png",
    "resistances": "Defense 150\n Fire 15\n Water 5\n Thunder -10\n Ice 5\n Dragon -15",
    "setBonus": "Increases Elemental Damage when landing critical hits",
    "headSkills": "Attack Boost 1x",
    "chestSkills": "Weakness Exploit 1x",
    "armSkills": "Fire Resistance 1x",
    "waistSkills": "Fire Attack 1x",
    "legSkills": "Jump Master 1x"
  },
    "rathian": {
    "title": "Rathian",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Rathian+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathian_armor_set_mhw_small.png",
    "resistances": "Defense 110\n Fire 10\n Water 0\n Thunder -10\n Ice 0\n Dragon -15",
    "setBonus": "None",
    "headSkills": "Health Boost 1x",
    "chestSkills": "Botanist 1x",
    "armSkills": "Poison Attack 1x",
    "WaistSkills": "Poison Resistance 1x",
    "legSkills": "Recovery Up 1x"
  },
    "ryu'samror": {
    "title": "Ryu's Armor",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Ryu's+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ryu_armor_set_mhw_small.png",
    "resistances": "Defense 66\n Fire 10\n Water 0\n Thunder 25\n Ice -15\n Dragon 10",
    "setBonus": "None",
    "headSkills": "Attack Boost 1x",
    "chestSkills": "HealthBoost 1x",
    "armSkills": "Latent Power 1x",
    "waistSkills": "Latent Power 1x",
    "legSkills": "Defense Boost 1x"
  },
    "shamos": {
    "title": "Shamos",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Shamos+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shamos_alpha_armor_set_mhw_small.png",
    "resistances": "Defense 22\n Fire 2\n Water 2\n Thunder 0\n Ice -3\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Detector 1x"
  },
    "tzitzi": {
    "title": "Tzitzi",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Tzitzi+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/tzitzi_armor_set_mhw_small.png",
    "resistances": "Defense 90\n Fire 0\n Water 0\n Thunder -15\n Ice -10\n Dragon 0",
    "setBonus": "None",
    "headSkills": "Blindsider 1x",
    "chestSkills": "Constitution 1x",
    "armSkills": "Stun Resistance 1x",
    "waistSkills": "Wide-Range 1x",
    "legSkills": "Sleep Resistance 1x"
  },
    "vespoid": {
    "title": "Vespoid",
    "url": "https://monsterhunterworld.wiki.fextralife.com/Vespoid+Armor+Set",
    "thumbnail": "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/vespoid_armor_set_mhw_small.png",
    "resistances": "Defense 40\n Fire -10\n Water 5\n Thunder 5\n Ice 5\n Dragon 10",
    "setBonus": "None",
    "headSkills": "Quick Sheath 1x",
    "chestSkills": "Windproof 1x",
    "armSkills": "Paralysis Attack 1x",
    "waistSkills": "Paralysis Resistance 1x",
    "legSkills": "Honey Hunter 1x"
    }  

}