if(command === "mhwalphahrarmor") {
  const listEmbed = new Discord.RichEmbed()
  .setColor('#8fde5d')
  .addField("Alpha High Rank Armor", "Alloy Alpha Armor Set\n Anja Alpha Armor Set\n Azure Starlord Alpha Armor Set\n Baan Alpha Armor Set\n Barnos Alpha Armor Set\n Barroth Alpha Armor Set\n Bazel Alpha Armor Set\n Blossom Alpha Armor Set\n Bone Alpha Armor Set\n Butterfly Alpha Armor Set\n Brigade Alpha Armor Set\n Chainmail Alpha Armor Set\n Commision Alpha Armor Set\n Damascus Alpha Armor Set\n Dante Alpha Armor Set\n Death Stench Alpha Armor Set\n Deviljho Alpha Armor Set\n Diablos Alpha Armor Set\n Diablos Nero Alpha Armor Set\n Diver Alpa Armor Set\n Drachen Alpha Armor Set\   n Dragonking Alpha Armor Set\n Dodogama Alpha Armor Set\n Dober Alpha Armor Set\n Faux Felyne Alpha Armor Set\n Gala Suit Alpha Armor Set\n Gajau Alpha Armor Set\n Gastadon Alpha Armor Set\n Girros Alpha Armor Set\n Guild Cross Alpha Armor Set\n High metal Alpha Armor Set\n Harvest Armor Set Alpha\n Hornetaur Alpha Armor Set\n Hunter's Alpha Armor Set\n Ingot Alpha Armor Set\n Jagras Alpha Armor Set\n Jyura Alpha Armor Set\n Kadachi Alpha Armor Set\n Kestodon Alpha Armor Set\n King Beetle Alpha Armor Set\n Kirin Alpha Armor Set\n Kulu Alpha Armor Set\n Kulu Ya Ku Head Alpha\n Kulve Taroth Alpha Armor Set\n Kushala Alpha Armor Set\n Lavasioth Alpha Armor Set\n Leather Alpha Armor Set\n Legiana Alpha Armor Set\n Lunastra Alpha Armor Set\n Lumu Alpha Armor Set\n Mosswine Alpha Armor Set\n Nergigante Alpha Armor Set\n Odogaron Alpha Armor Set\n Orion Armor Alpha Set\n Pukei Alpha Armor Set\n Rath Heart Alpha Armor Set\n Rath soul Alpha Armor Set\n Rathalos Alpha Armor Set\n Rathian Alpha Armor Set\n Ryu's Alpha Armor Set\n Sakura's Alpha Armor Set\n Shamos Alpha Armor Set\n Strategist Alpha Armor Set\n Teostra Alpha Armor Set\n Tzitzi Alpha Armor Set\n Uragaan Alpha Armor Set\n Vaal Hazak Alpha Armor Set\n Vespoid Alpha Armor Set\n Xeno'jiiva Alpha Armor Set\n Zorah Alpha Armor Set\n  )
  .setTimestamp()
  .setFooter('List Menu');
    
  message.channel.send(listEmbed);
}
